version: "3.8"
services:
  vscode:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    command: bash -c 'echo Container started ; while sleep 1; do :; done'
    working_dir: /workspace
    volumes:
      - ../:/workspace
    ports:
      - "9999:9999"
    security_opt:
      - seccomp:unconfined
    cap_add: 
      - SYS_PTRACE
  prom:
    image: prom/prometheus:v2.53.1
    entrypoint: ["/tmp-prometheus/entrypoint.sh"]
    command: >
      --config.file=/etc/prometheus/prometheus.yml 
      --storage.tsdb.path=/prometheus 
      --storage.tsdb.allow-overlapping-blocks
      --storage.tsdb.retention.time=30d
      --web.console.libraries=/usr/share/prometheus/console_libraries 
      --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - "../:/workdir"
      - "./prometheus:/tmp-prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:master
    volumes:
      - "./grafana-data:/var/lib/grafana"
    ports:
      - "3000:3000"
